kubescape/k8s-interface

- cloudsupport/v1/ekssupport.go
This is related to the issue no. #670 on the kubescape repo. I have added a method for obtaining the roles/user from aws-auth configmap
> method for obtaining the roles/user from aws-auth configmap is added

- k8sinterface/k8sdiscovery.go
Load the different types of supported objects from the discovery API and not from mock data
> Load resources from discovery

- k8sinterface/k8sstatic.go
- workloadinterface/interface.go
- workloadinterface/testdata/workloadmethods/podstatusnotpresent.json
- workloadinterface/testdata/workloadmethods/podstatusrunning.json
- workloadinterface/workloadmethods.go
- workloadinterface/workloadmethods_test.go
- workloadinterface/workloadmock.go
1 - add `GetPodStatus` function
2 - Change `ListPods` to return an object of type `*corev1.PodList`, instead of returning just the list of Pods themselves. The reason is since some clients may need to access data from the PodList object, such as ResourceVersion, and we shouldn't limit it.
> Add GetPodStatus and update ListPods

- cloudsupport/v1/akssupport.go
- cloudsupport/v1/akssupportmock.go
Hi @dwertent , 
Related to : Enrich RoleBinding/ClusterRoleBinding objects with cloud vendor infromation #670
for Azure AKS Cluster
I've added support for getting groupIds/ UPN for single azure users from the rolebindings/clusterrolesbindings.
kindly Review.
> function for getting groupid's from rolebindings is added

- cloudsupport/apis/apis.go
- cloudsupport/cloudproviderconfiguration.go
- cloudsupport/mockobjects/cloudmockobjects.go
- cloudsupport/v1/cloudproviderv1.go
- cloudsupport/v1/cloudproviderv1_test.go
- cloudsupport/v1/datastructures.go
- cloudsupport/v1/ekssupport.go
- cloudsupport/v1/ekssupportmock.go
- cloudsupport/v1/methods.go
This feature implement the following command from `aws` cli:
```
aws iam get-policy-version --version-id v3 --policy-arn arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
```
In this way, we will be able to retrieve policy version contents from AWS and provide them to the **rego** rules.
More specifically, we are filling the missing data for this issue: [SUB-610](https://cyberarmor-io.atlassian.net/browse/SUB-610).
Here's an example about what we are going to have:
```
{
"apiVersion": "eks.amazonaws.com/v1",
"kind": "PolicyVersion",
"metadata": {
"name": "ca-terraform-eks-dev-stage",
"provider": "eks"
},
"data": {
"policiesDocuments": {
"arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly": {
"Version": "2012-10-17",
"Statement": [
{
"Effect": "Allow",
"Action": [ …
```
> feat(cloudsupport): implement get-policy-version funtionality

- instanceidhandler/errors.go
A previous commit has erroneusly introduced an exported error which was never used anywhere. This commit removes the error.
> fix(instanceidhandler): remove unused error

- k8sinterface/k8sconfig.go
- k8sinterface/k8sconfig_test.go
Bug fix, Tests
Resolves: [After upgrade to 2.9.0 framework cis-aks-t1.2.0 not working](https://github.com/kubescape/kubescape/issues/1350)
___
This PR addresses an issue with the retrieval of the server name of a desired cluster context. The logic has been updated to handle different scenarios more accurately. Additionally, tests have been added to ensure the correct functionality of the updated method.
___
`k8sinterface/k8sconfig.go`: Updated the GetK8sConfigClusterServerName function to handle different scenarios such as when the config is nil, when the context name is not set, and when the server name is not available. The function now returns the appropriate server name based on these conditions.
`k8sinterface/k8sconfig_test.go`: Added tests for the GetK8sConfigClusterServerName …
> Fixing Cluster Server Name Retrieval and Adding Corresponding Tests

- workloadinterface/testdata/workloadmethods/deploymentWithemptyLabels.json
- workloadinterface/workloadmethods.go
- workloadinterface/workloadmethods_test.go
Bug fix, Tests
___
This PR addresses a bug where the `GetLabels` method was causing a panic when a label value was nil. The fix involves checking for nil values and ignoring them. Additionally, a test case has been added to ensure that null labels are not returned.
___
`workloadinterface/workloadmethods.go`: Added a check for nil values in the `GetLabels` method. If a label value is nil, it is now ignored.
`workloadinterface/workloadmethods_test.go`: Added a new test case for the `GetLabels` method to ensure that null labels are not returned.
`workloadinterface/testdata/workloadmethods/deploymentWithemptyLabels.json`: Added a new test data file that contains a deployment with null labels. This is used in the new test case for the `GetLabels` method.
___
`GetLabels` was panicking when a …
> check for nil value in  labels

- names/slugs.go
- names/slugs_test.go
Enhancement
___
This PR introduces slug generation for configuration scan resources. It adds a new function to convert any string into a slug, and two other functions to convert a resource and a role binding resource into slugs. The slug is a human-friendly representation based on the API version, kind, namespace, and name of the resource. The PR also includes relevant tests to ensure the functionality of the new slug generation methods.
___
`names/slugs.go`: Added new functions for slug generation: `StringToSlug`, `ResourceToSlug`, and `RoleBindingResourceToSlug`. These functions convert a string, a resource, and a role binding resource into slugs, respectively. Also, some constants and existing functions were updated to accommodate these changes.
`names/slugs_test.go`: Added tests for …
> Generate slugs for configuration scan resources

- cloudsupport/cloudproviderconfiguration.go
- cloudsupport/v1/cloudproviderv1.go
- cloudsupport/v1/cloudproviderv1_test.go
Refactoring
___
This PR refactors the method of detecting the cloud provider in the Kubescape project. Previously, the cloud provider was detected based on the gitVersion/server URL. Now, it is detected based on the labels of the nodes in the Kubernetes cluster. This change improves the accuracy of cloud provider detection.
___
<details> <summary>files:</summary>
`cloudsupport/cloudproviderconfiguration.go`: The GetCloudProvider function has been updated to accept a NodeList parameter. This is used to determine the cloud provider.
`cloudsupport/v1/cloudproviderv1.go`: The GetCloudProvider function has been updated to accept a NodeList parameter. The IsGKE, IsAKS functions have also been updated to use the NodeList for cloud provider detection. A new helper function, labelHasCloudPrefix, …
> Get cloud provider from the nodes labels

- workloadinterface/testdata/workloadmethods/podmountnohostvolume.json
- workloadinterface/testdata/workloadmethods/podmountwithvolume.json
- workloadinterface/workloadmethods.go
- workloadinterface/workloadmethods_test.go
Enhancement
___
This PR introduces three new functions to the workload interface, aimed at providing more information about the volumes used in workloads. These functions are:
1. `GetVolumeMountsPaths`: Returns all volume mount paths of the workload, with options to filter by read-only status and whether the volume is a host volume.
2. `GetHostVolumes`: Returns all host volumes of the workload.
3. `GetSpecPathPrefix`: Returns the path prefix of the workload spec, depending on the kind of the workload.
The PR also includes relevant unit tests for these new functions.
___
<details> <summary>files:</summary>
`workloadinterface/workloadmethods.go`: Added three new functions: `GetVolumeMountsPaths`, `GetHostVolumes`, and `GetSpecPathPrefix`. Also, added a new struct `VolumeMount` to represent …
> workload volume functions

- workloadinterface/interface.go
- workloadinterface/workloadmethods.go
- workloadinterface/workloadmethods_test.go
- workloadinterface/workloadmock.go
Enhancement
___
This PR introduces a new method to retrieve the selector from Service kind objects. The previous `GetSelector` function was not compatible with `Service` kind as the `selector` has a different type. The new method `GetServiceSelector` returns a map of strings, allowing it to work with the `Service` kind.
___
<details> <summary>files:</summary>
`workloadinterface/interface.go`: Added a new method `GetServiceSelector` to the `IBasicWorkload` interface.
`workloadinterface/workloadmethods.go`: Implemented the `GetServiceSelector` method in the `Workload` struct. This method inspects the workload and retrieves the service selector if it exists.
`workloadinterface/workloadmethods_test.go`: Added a new test `TestGetServiceSelector` to verify the correct functionality of the …
> support service selector

- instanceidhandler/v1/instanceidhandler.go
Enhancement
___
This PR introduces a new constant, `ResourceVersionMetadataKey`, to the `instanceidhandler.go` file. This key is intended to be used for storing the workload resource version.
___
<details> <summary>files:</summary>
- `instanceidhandler/v1/instanceidhandler.go`: Added a new constant `ResourceVersionMetadataKey` for storing the workload resource version.
</details>
> add ResourceVersionMetadataKey for related wl version

- instanceidhandler/v1/instanceidhandler.go
- instanceidhandler/v1/instanceidhandler_test.go
- names/slugs.go
- names/slugs_test.go
Enhancement
___
This PR focuses on changing the naming convention of slugs in the application. The main changes include:
- Removing the namespace and hash from the slug format.
- Updating the `GetSlug` method in `instanceidhandler.go` and its corresponding tests to reflect this change.
- Removing the `GetNamespaceLessSlug` method from `slugs.go`.
- Updating the `InstanceIDToSlug`, `sanitizeInstanceIDSlug`, `StringToSlug`, and `ResourceToSlug` methods in `slugs.go` and their corresponding tests to reflect these changes.
___
<table><thead><tr><th></th><th>Relevant files&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> remove hash and ns from name

- instanceidhandler/v1/instanceidhandler.go
enhancement
___
- Added a new constant `TemplateHashKey` to the metadata keys in `instanceidhandler.go`. This key will be used for instance template hash.
___
<table><thead><tr><th></th><th>Relevant files&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><details><summary>1 files</summary><table>
<tr>
<td> …
> adding TemplateHashKey

- workloadinterface/workloadmethods.go
- workloadinterface/workloadmethodsutils.go
- workloadinterface/workloadmethodsutils_test.go
enhancement, tests
___
- Added a new functionality in `workloadinterface/workloadmethods.go` to handle the case where the workload is a Pod with a `pod-template-hash` label. In this case, it generates a `ReplicaSet` from the pod hash and appends it to the `ownerReferences`.
- Implemented a new function `getReplicasetNameFromPod` in `workloadinterface/workloadmethodsutils.go` that constructs a `ReplicaSet` name from a given pod name and pod template hash.
- Added unit tests in `workloadinterface/workloadmethodsutils_test.go` for the new function `getReplicasetNameFromPod` to validate its functionality.
___
<table><thead><tr><th></th><th>Relevant files&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> generate replicaset from pod hash

- cloudsupport/v1/ekssupport.go
- cloudsupport/v1/ekssupport_test.go
Here is the error log:
```
{"level":"info","ts":"2024-02-06T13:36:52Z","msg":"credentials loaded from path","path":"/etc/credentials","accessKeyLength":36,"accountLength":36}
{"level":"info","ts":"2024-02-06T13:36:52Z","msg":"Starting swagger UI. baseURI: /openapi/v2/, docsEP: docs, rapidocEP: rapi, swaggerui: swaggerui"}
{"level":"info","ts":"2024-02-06T13:36:52Z","msg":"Started Kubescape server","port":"8080","version":""}
{"level":"info","ts":"2024-02-06T13:37:01Z","msg":"REST API received scan request","body":"{\"targetNames\":[\"allcontrols\",\"nsa\",\"mitre\",\"security\"],\"targetType\":\"Framework\",\"hostScanner\":false}"}
{"level":"info","ts":"2024-02-06T13:37:01Z","msg":"requesting scan","scanID":"9bf77782-58c5-4be4-8736-96f81ba1e471","api":"v1/scan"} …
```
> Fixed parse eks region

- instanceidhandler/v1/helpers/keys.go
enhancement
___
- Introduced a new metadata key `ResourceSizeMetadataKey` to track the size of resources.
- Added new statuses (`Partial`, `Full`, `MissingRuntime`, `TooLarge`) to provide more detailed information about the state of resources.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>keys.go</strong><dd><code>Add Resource Size Metadata Key and New Status Constants</code>&nbsp; &nbsp; </dd></summary>
<hr>
instanceidhandler/v1/helpers/keys.go
<li>Added <code>ResourceSizeMetadataKey</code> constant for tracking resource size.<br> <li> Introduced new statuses: <code>Partial</code>, <code>Full</code>, <code>MissingRuntime</code>, and <code>TooLarge</code> …
> adding new consts for KDR feature

- instanceidhandler/v1/helpers/keys.go
Part of : https://github.com/kubescape/helm-charts/pull/408/files
___
enhancement
___
- Introduced a new metadata key `TierMetadataKey` to categorize resources by tier.
- Added a constant `CoreTier` to define core tier resources, enhancing the metadata categorization.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>keys.go</strong><dd><code>Introduce Tier Metadata and Core Tier Constant</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
instanceidhandler/v1/helpers/keys.go
<li>Added a new constant <code>TierMetadataKey</code> for tier metadata.<br> <li> Introduced a new constant <code>CoreTier</code> …
> Added tier label

- cloudsupport/apis/apis.go
- go.mod
- go.sum
- k8sinterface/k8sdynamic.go
The experimental functions in `golang.org/x/exp/slices` are now available in the standard library in Go 1.21.
Reference: https://go.dev/doc/go1.21#slices
> Replace `golang.org/x/exp/slices` with `slices` from stdlib

- cloudmetadata/metadata.go
- cloudmetadata/metadata_test.go
- cloudmetadata/testdata/linode.json
- cloudsupport/v1/cloudproviderv1.go
- cloudsupport/v1/cloudproviderv1_test.go
I noticed kubescape didn't recognize Linode, so I added it.
> fix: add missing linode cloud provider
